services:
     - type: web
       name: ai-insider-threat-detection-api
       runtime: node
       rootDir: server
       buildCommand: npm install
       startCommand: npm start
       envVars:
         - key: MONGO_URI
           sync: false
         - key: CLIENT_URL
           sync: false
         - key: PORT
           value: 5000
